server:
  port: 9101
  servlet:
    context-path: /money-pos

spring:
  application:
    name: qk-money
  profiles:
    active: dev # 默认开发环境
    include: [ money ]

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger配置
swagger:
  scan-package: com.money
  title: ${spring.application.name}
  description: ${spring.application.name}接口文档
  version: 1.0.0
  auth-header: ${money.security.token.header}
  contact:
    name: money
    url: www.money.com
    email: 374648769@qq.com
  external-documentation:
    url: https://github.com/ycf1998
    description: github